### ISSUE TITLE
backport?

### ISSUE THREAD

**Issue by RYUKxAnime** [Greeenman999/LibrarianTradeFinder#16]

**Comment by beabfc** [comment]
I backported the latest version to 1.19.2:

https://github.com/beabfc/LibrarianTradeFinder/releases/tag/1.19.2-backport

**Comment by RYUKxAnime** [comment]
sorry i wasn’t specific 
I meant backport for 1.17.1?
are you willing to do that?

**Comment by beabfc** [comment]
1.17 would
