### ISSUE TITLE
1.20

### ISSUE THREAD

**Issue by Bcreade07** [Greeenman999/LibrarianTradeFinder#20]
is there a 1.20 release date? It would be an amazing mod to have rn lmao. thx

**Comment by NotNite** [comment]
I did a very lazy update over [here](https://github.com/NotNite/LibrarianTradeFinder), really the only changes required is updating YACL.

**Comment by Bcreade07** [comment]
hey sorry im kinda stupid how do i download it from that link bec the new YACL dosent seem to work. do i go w the 1.19.4 version w the newest YCAL or am i just dumb and dont understand how to download it?

**Comment by NotNite** [comment]
I'm not telling you to download it from my fork. The developer of this mod can look at the changes I made to implement it officially.

**Comment by Greeenman999** [comment]
Closing because i released 1.20 :D
