### ISSUE TITLE
Doesen't work wirh 3 or less

### ISSUE THREAD

**Issue by Heliecraft** [Greeenman999/LibrarianTradeFinder#21]
When I use the mod i need  atleast 4 lecturns so that IT works but wenn I play suriviel i offen don't have more than 1.
So mabey you could make It so It works with only 1 or 2.

**Comment by Greeenman999** [comment]
Hi, unfortunately i can't do anything about it, because its related to how minecrafts drops items. Sometimes they glitch behind the lectern and sometimes not. Enabling the `Teleport to Villager` Toggle should help though!

**Comment by Heliecraft** [comment]
Also in the beta 1.20 Version the c for Confic doesn't work

**Comment by Greeenman999** [comment]
Maybe something other is set to this key. Please check in your Controls

**Comment by Greeenman999** [comment]
Closing this now.
