### ISSUE TITLE
Change price doesnt work

### ISSUE THREAD

**Issue by Sethyla** [Greeenman999/LibrarianTradeFinder#22]
![image](https://github.com/Greeenman999/LibrarianTradeFinder/assets/138025045/058b4872-c25b-4053-9f12-ef0a0767c04c)
when I change the $ amount nothing happens, someone pls help?

**Comment by Greeenman999** [comment]
Hi, do you mean typing something in doesnt work?

**Comment by msfjarvis** [comment]
Yes, typing in the textbox does not work. Keyboard input doesn't go through, the price stays stuck at 64.

**Comment by XavierBit** [comment]
It's strange, as sometimes it works. You have to click just to the right of the number you want to change. So let's say the price is at 64, click right to the 6 and change this value. Then click right to the 4 and change this one. 
The problem I have is when I change a value to a one digit number, I can't use the second digit anymore, the cursor stays flat on the ground and no input is possible.
![Screenshot_91](https://github.com/Greeenman999/LibrarianTradeFinder/assets/95314871/46247321-852b-46ec-8c84-11cc4795fa55)

**Comment by SorkoPiko** [comment]
> Hi, do you mean typing something in doesnt work?

Yes, it is very buggy and only lets you type something into the box sometimes, under unknown circumstances. The fix shown above also sometimes works. If you could fix this, it would be great. Amazing mod, can't wait to see it improve. Thanks!

**Comment by glowstone314** [comment]
取消选择附魔，然后重新选择，就能修改了。但只能用退格(Backspace)不能用删除(Delete)

**Comment by Greeenman999** [comment]
This will be fixed in the next update!
