### ISSUE TITLE
Make a 1.16.x version 

### ISSUE THREAD

**Issue by fuddu-sama** [Greeenman999/LibrarianTradeFinder#24]
I understand, you have made Librarian Finder Mod for newer versions. But there are few servers and players who play in older mods. So it would be awesome if you made a 1.16.x version.

**Comment by SorkoPiko** [comment]
just use viafabric and 1.20

**Comment by Greeenman999** [comment]
Hi, a backport is currently not planned (maybe sometime in the future)
