### ISSUE TITLE
Option for custom enchantments

### ISSUE THREAD

**Issue by capriozir** [Greeenman999/LibrarianTradeFinder#33]
It would be cool if you could Input the name of a modded enchantment and serch for it as well.

**Comment by Greeenman999** [comment]
Hey man, it should work with modded enchantments too, if you can check and send me some additional details, I'm going to fix this. Thanks for your report!

**Comment by capriozir** [comment]
> Hey man, it should work with modded enchantments too, if you can check and send me some additional details, I'm going to fix this. Thanks for your report!

It works indeed with client side mods, but when I was playing on papermc server with EcoEnchants they don't show up

**Comment by Greeenman999** [comment]
Ah yea. Thats because of the clients registry which the mod reads. Im going to further investigate how I could fix this.

**Comment by Greeenman999** [comment]
Yea sorry, I think its impossible to fix this, because of the registries.

**Comment by capriozir** [comment]
so I can't even add the custom names to a file somewhere inside the jar?
