### ISSUE TITLE
1.20.2 Support

### ISSUE THREAD

**Issue by tunaflsh** [Greeenman999/LibrarianTradeFinder#38]
Crashes when opening config.

[crash-2023-10-14_20.38.35-client.txt](https://github.com/Greeenman999/LibrarianTradeFinder/files/12907442/crash-2023-10-14_20.38.35-client.txt)

**Comment by Greeenman999** [comment]
Thanks for reporting, I will fix this soon!

**Comment by Greeenman999** [comment]
Fixed in the next version.
