### ISSUE TITLE
Swing left arm when placing lectern

### ISSUE THREAD

**Issue by RamTamDe** [Greeenman999/LibrarianTradeFinder#39]
Player does not swing left arm when placing lectern. The mod works fine, but it looks awkward. Could you please fix it? Thank you for developing a great mod.

**Comment by RamTamDe** [comment]
It was so fast! Thank you for your efforts.

**Comment by RamTamDe** [comment]
> Hey, thanks for your suggestion, I will add this to my todo list!

hello. While checking the mod, I noticed that off-hand swing packets are not being sent to the server. Is there a reason? Thank you again for your quick response.

player.networkHandler.sendPacket(new HandSwingC2SPacket(Hand.OFF_HAND));

**Comment by Greeenman999** [comment]
Oops, yea i forgot that, I'm going to release new version later this day! Thank you for notifying me.

**Comment by RamTamDe** [comment]
> hello. While checking the mod, I noticed that off-hand swing packets are not being sent to the server. Is there a reason? Thank you again for your quick response.

Great! Thanks again!
