### ISSUE TITLE
Please Update to 1.21 version [FEATURE]

### ISSUE THREAD

**Issue by AHMatomicx** [Greeenman999/LibrarianTradeFinder#55]
the mod is amazing and withe the new mc 1.21 comes some new enchants so please can you update

**Comment by eivinhb** [comment]
I made #56. it works for me now.

**Comment by theskulliv** [comment]
> I made #56. it works for me now.

can you tell me how to download this as a .jar ?

im sorry i don't know anything in github coding

**Comment by eivinhb** [comment]
See the issue: https://github.com/Greeenman999/LibrarianTradeFinder/pull/56#issuecomment-2183976363 find the download artifacts. You will get a zip with Jar and sources-jar. You dont need the sources.

**Comment by theskulliv** [comment]
@eivinhb Thank you so much for your help, it worked100% 🙃

**Comment by toetagger** [comment]
> > I made #56. it works for me now.
> 
> can you tell me how to download this as a .jar ?
> 
> im sorry i don't know anything in github coding

For anyone following along. In order to see the Download Artifact button _you have to be signed in_ ....... No one told me and I struggled for about 20 mins :')

**Comment by HotHyper** [comment]
Hello, how to use for V 1.21 of minecraft?
