### ISSUE TITLE
Trades checking too fast

### ISSUE THREAD

**Issue by somebirby** [Greeenman999/LibrarianTradeFinder#6]
The search gets stuck on the first or second attempt, because it seems it's trying to check the villager much too soon, before it can get the job:
https://user-images.githubusercontent.com/16958149/216428904-ef8fb99f-a231-45ad-ae08-47bc9b0c2d5c.mp4

Maybe at re-attempts to read the villager's trades, or a configurable delay for it.

Otherwise, great job, thanks for your work 😄

**Comment by Greeenman999** [comment]
Thanks for reporting, it will be fixed in the next update, probably releasing tomorrow or on saturday.

**Comment by somebirby** [comment]
Do you have an ETA on the next update?

**Comment by Greeenman999** [comment]
Sorry, I had a lot to do and forgot this, could you test if this build resolves your issue? https://cdn.discordapp.com/attachments/1072312903564283965/1072579909823762513/librarian-trade-finder-1.0.0.jar
