### ISSUE TITLE
Use with Trade Cycling

### ISSUE THREAD

**Issue by emorygg** [Greeenman999/LibrarianTradeFinder#7]
It would be awesome if there was support with [Trade Cycling](https://modrinth.com/mod/trade-cycling). You would select a villager as you normally do then it would open the gui and cycle the trades until it found the trade you submitted.

Also, I think that it would be nice to have the min/max trade price listed when type in the command. So Thorns III for example would show something like "price: 11-45".

**Comment by Greeenman999** [comment]
Thanks for your feedback! 
1. Support with Trade Cycling: I don't really understand why you would want to do it manually?
2. Min/Max Price List: I really like this idea and will try to implement it in the future.

Have a great day!
